apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: app
  labels:
    deploy: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: alberth1414/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: GIT_URI
              value: https://github.com/alberthgr1414/Config
            - name: GIT_USERNAME
              value: alberthgarita
            - name: GIT_PASSWORD
              value: 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
            - name: GIT_BRANCH
              value: main
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  namespace: app
spec:
  selector:
    app: configserver
  ports:
    - name: amqp
      protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
