apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: common
  labels:
    deploy: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: alberth1414/config-server:latest
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: common
spec:
  selector:
    app: configserver
  ports:
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer